### PR TITLE
Implement user homepage and (more) sketch tests.

### PR DESCRIPTION
**Pull request by bduffany**
From #1, I've implemented the following checked items in this pull request:

User's homepage
- [x] Create new project with no project name
- [x] Create new project with valid project name
- [x] Create new project with invalid name (e.g. backslashes in project name)

Sketch page
- [x] Open Serial Monitor with empty ports dropdown

As @hciwork has noted in #2, it's tricky to test uploads. It's not possible to do with Selenium alone, unless the upload occurs via an `<input type="upload">` element, in which case the absolute path of the file can be directly entered using `send_keys`. Otherwise, it's necessary to use some sort of library to interact with the file upload dialogue box. It may or may not be possible to achieve this with [Robot Framework](http://robotframework.org/). I'm looking into it.

Update: the following from #1 are resolved in #7:

- [x] Upload project (single file)
- [x] Upload project (need to test zip functionality, is that possible?)

### CODE REVIEW

**Comment by bduffany** [comment]
As it turns out, Robot Framework didn't really have any useful automation tools to automate the dialogue boxes, it just provided its own "language" to interface with Selenium, and not much more than that. See [my comment](https://github.com/codebendercc/seleniumTests/issues/3#issuecomment-77543030) on #3.

**Comment by bduffany** [comment]
I've resolved the first and last tasks (testing uploads) in #7.

**Comment by bduffany** [comment]
Think we can start pulling these in? Also how should we deal with the conflict? Should I merge the branch myself so that I can resolve it?

**Comment by spiliot** [comment]
@bduffany Sorry for this huge delay in looking at the PRs but somehow I never got notifications from this repo. 

Regarding this branch, I see that there are merge conflicts, you should resolve those first.

**Comment by bduffany** [comment]
I pulled master and resolved a conflict with some of @hciwork's earlier changes from master.

**Pull request merged**
